setting_terms:
  - Dune
  - Arrakis
  - Caladan
  - CHOAM
  - Landsraad
  - Spacing Guild
  - Bene Gesserit
  - Mentat
  - Sardaukar
  - Fremen
  - melange
  - spice

rpg_terms:
  - asset
  - momentum
  - threat
  - drive
  - duty
  - faith
  - discipline
  - battle
  - communicate
  - move
  - understand

campaign_terms:
  - bespoke spacecraft
  - shipyard
  - treasury
  - ledger
  - House venture
